# action名称
name: deploy-website

# 当代码合并到master分支的时候，执行下列脚本
on:
  push:
    branches: [master]
# 任务
jobs:
  # docs-build为任务id可随意定义
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: 切换到master分支拉取源码
        uses: actions/checkout@master

      - name: 安装指定版本的Node.js
        uses: actions/setup-node@master
        with:
          node-version: "18.X"
          # registry-url: https://registry.npmjs.org/ # 如果不配置将影响publish

      - name: 安装依赖
        run: npm install

      - name: 构建dist
        run: npm run build

      - name: build 成功通知
        run: echo npm 构建成功，请访问 http://8.134.54.104

      - name: copy file via ssh password
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '~/blog'
          EXCLUDE: "/build/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT


